### ISSUE TITLE
The UI does not refresh to show Top 11 or Centered +/- 5 leaderboards

### ISSUE THREAD

**Issue by gmflau** [GoogleCloudPlatform/memstore-gaming-leaderboard#3]
I tried to deploy the leaderboard application along with the use of MemoryStore (Redis).  It looks like the submit button is not creating/updating records in the MemoryStore (Redis db).  The page did refresh with new set of questions after pressing the submit button. However, the leaderboard below is always empty.

**Comment by joeholley** [comment]
Addressed by latest commit; thanks for the heads up!
